-- Add images360 column to all tables
ALTER TABLE artisans ADD COLUMN IF NOT EXISTS images360 JSON DEFAULT NULL;
ALTER TABLE sejours ADD COLUMN IF NOT EXISTS images360 JSON DEFAULT NULL;
ALTER TABLE caravanes ADD COLUMN IF NOT EXISTS images360 JSON DEFAULT NULL;
